name: Godot Web Export and Deploy

on:
  push:
    branches: [master]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create export directory
        run: mkdir -p build/web

      - name: Export HTML5 build using Godot
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/game \
            -w /game \
            barichello/godot-ci:4.4.1 \
            godot --headless --export-release "Windows Desktop" build/web/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web